// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABX8CnXvlwESC01p9cvw2byBW4j0l6pEA',
    appId: '1:584512198614:web:38778c71d8a15f6bad3677',
    messagingSenderId: '584512198614',
    projectId: 'flutter-app-5d660',
    authDomain: 'flutter-app-5d660.firebaseapp.com',
    storageBucket: 'flutter-app-5d660.appspot.com',
    measurementId: 'G-L3HTLZ98SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAO9rsqQ0b2CUDdWV1BZzJjRbXWVGwgJg',
    appId: '1:584512198614:android:5ac8261891842b20ad3677',
    messagingSenderId: '584512198614',
    projectId: 'flutter-app-5d660',
    storageBucket: 'flutter-app-5d660.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUjpmrmcdgFHh9mNoxLiPSAu4uPbmJ1a0',
    appId: '1:584512198614:ios:a77ff4145cf31d8dad3677',
    messagingSenderId: '584512198614',
    projectId: 'flutter-app-5d660',
    storageBucket: 'flutter-app-5d660.appspot.com',
    androidClientId: '584512198614-20kpp7dqehskrc0i04tf33tr80778ng0.apps.googleusercontent.com',
    iosClientId: '584512198614-q99tquhaef3eup950gq72qqi11puat2j.apps.googleusercontent.com',
    iosBundleId: 'com.example.registrationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUjpmrmcdgFHh9mNoxLiPSAu4uPbmJ1a0',
    appId: '1:584512198614:ios:cbfe9101232aab29ad3677',
    messagingSenderId: '584512198614',
    projectId: 'flutter-app-5d660',
    storageBucket: 'flutter-app-5d660.appspot.com',
    androidClientId: '584512198614-20kpp7dqehskrc0i04tf33tr80778ng0.apps.googleusercontent.com',
    iosClientId: '584512198614-sr16lt24lt5hfgdb6gfa2l2j7h59esfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.registrationApp.RunnerTests',
  );
}
